[package]
name = "rust_web_scraper"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.9", features = ["blocking", "json"] }
select = "0.6.0"
tokio = { version = "1.41.0", features = ["full"] }
